"""Add gamification fields to User

Revision ID: f5c8d1966aa6
Revises: aed53f4858c4
Create Date: 2026-01-02 00:34:57.754747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c8d1966aa6'
down_revision = 'aed53f4858c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('diamonds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('health', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_active_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_active_date')
        batch_op.drop_column('health')
        batch_op.drop_column('diamonds')
        batch_op.drop_column('streak')

    # ### end Alembic commands ###
